### PR TITLE
Fix data.azurerm_client_config.current.object_id return "" empty when upgrading az cli to 2.37.0

### PR DESCRIPTION
**Pull request by backwind1233**
Context

When running samples with terraform, the same issue happens as the https://github.com/hashicorp/terraform-provider-azurerm/issues/16982 described.

Solution
Upgrade version of hashicorp/azurerm to 3.9.0.

Checklist:
- [ ] Test all samples with terraform.

### CODE REVIEW

**Comment by saragluna** [comment]
Do we test them one by one? I remember having issues running one of the Event Hubs samples, but I don't know which one it is.

**Comment by backwind1233** [comment]
> Do we test them one by one? I remember having issues running one of the Event Hubs samples, but I don't know which one it is.

I will test them one by one.

**Comment by backwind1233** [comment]
close this pr, there are breaking changes for hashicorp/azurerm from 2.x.x to 3.x.x,  which is not compatible with our original code.

**Comment by backwind1233** [comment]
Here is the result of running terraform scripts with different hashicorp/azurerm versions:


Module|Version
-- | --
Az Cli version | 2.38.0
terraform Version | v1.2.4 on darwin_arm64
hashicorp/azurerm | 3.9.0



CleanShot 2022-07-11 at 13 34 26@2x

----
Module|Version
-- | --
Az Cli version | 2.38.0
terraform Version | v1.2.4 on darwin_arm64
hashicorp/azurerm | 2.99.0

CleanShot 2022-07-11 at 13 36 28@2x

**Comment by backwind1233** [comment]
Link this pr with https://github.com/Azure-Samples/azure-spring-boot-samples/issues/430.

**Pull request closed without merging**
