### PR TITLE
Fix links in AAD readme file

### PR DESCRIPTION
**Pull request by saragluna**
As title.

### CODE REVIEW

**Review by chenrujun — APPROVED** [review]
LGTM.

**Review by backwind1233 — APPROVED** [review]
LGTM

**Comment by backwind1233** [comment]
The commit in this PR is cherry-picked into PR:https://github.com/Azure-Samples/azure-spring-boot-samples/pull/296

**Comment by saragluna** [comment]
Close in favor of https://github.com/Azure-Samples/azure-spring-boot-samples/pull/300.

**Pull request closed without merging**
