### PR TITLE
Update Spring Cloud Azure version to 4.4.1

### PR DESCRIPTION
**Pull request by Netyyyy**
As title.

### CODE REVIEW

**Review by chenrujun — CHANGES_REQUESTED** [review]
We should merge to [spring-cloud-azure_v4.4.0](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_v4.4.0/pom.xml) branch instead of main branch.

**Comment by Netyyyy** [comment]
close and work on https://github.com/Azure-Samples/azure-spring-boot-samples/pull/542

**Comment by saragluna** [comment]
> We should merge to [spring-cloud-azure_v4.4.0](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_v4.4.0/pom.xml) branch instead of main branch.

You meant the `4.4.1` branch, right?

**Comment by chenrujun** [comment]
> You meant the 4.4.1 branch, right?

@saragluna , yes, create a new branch named **spring-cloud-azure-v4.4.1** from **spring-cloud-azure-v4.4.0**. Here is the PR: https://github.com/Azure-Samples/azure-spring-boot-samples/pull/542

**Pull request closed without merging**
