### PR TITLE
Manually upgrade spring-boot-starter-parent to 2.6.7

### PR DESCRIPTION
**Pull request by Netyyyy**
As title.
Refer to https://github.com/Azure-Samples/azure-spring-boot-samples/pull/274.
Try to awake dependabot.

### CODE REVIEW

**Comment by Netyyyy** [comment]
@dependabot reopen

**Review by backwind1233 — APPROVED** [review]
LGTM

**Comment by Netyyyy** [comment]
@dependabot recreate

**Comment by Netyyyy** [comment]
@dependabot rebase

**Comment by Netyyyy** [comment]
@dependabot

**Pull request merged**
